### ISSUE TITLE
AzureStack  ADFS login SPN

### ISSUE THREAD

**Issue by MilanNXT** [terraform-providers/terraform-provider-azurestack#11]
It seems current provider would work only with AAD deployed AZS. I haven't found anywhere how to configure SPN with certificate for ADFS deployed AZS.

**Comment by dmc-tech** [comment]
This is a feature I also require.  Is anyone working on this?  I see more and more customers deploying Azure Stack with AD FS as the identity provider.

**Comment by dmc-tech** [comment]
The Azure Stack Go SDK includes the option for using certificate based auth so should be possible? https://github.com/Azure/azure-sdk-for-go#more-authentication-details

**Comment by tombuildsstuff** [comment]
@dmc-tech to give an update here: this is something we'd need to implement across all the Azure Providers (AzureRM, Azure Stack and the Azure Backend). It's something we're thinking about at the moment but we're holding off until we're able to make the changes to the Backend (since we're planning on pulling this logic out into a shared package at the same time) - which is currently blocked on some work happening for Terraform 0.12 - however once that's released we should be able to proceed with adding support for this :)

**Comment by dmc-tech** [comment]
Thanks @tombuildsstuff .  Will be good to have Packer integration too, so totally makes sense.

**Comment by MilanNXT** [comment]
That would be great, looking forward

**Comment by tombuildsstuff** [comment]
👋 

To give an update here: [the authentication package has been split out from AzureRM](https://github.com/hashicorp/go-azure-helpers) - which has support for Client Certificate authentication. We're working on integrating that at the moment - once that's been merged we'll then add the documentation and enable Client Certificate authentication in a subsequent update :)

Thanks!

**Comment by bottkars** [comment]
is the support for ADFS implemented now or still pending ??
